CREATE TABLE deliveries
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id      INTEGER                                  NOT NULL,
    status        TEXT                                     NOT NULL,
    delivery_date timestamptz                              NOT NULL,
    created_at    timestamptz default clock_timestamp(),
    CONSTRAINT pk_deliveries PRIMARY KEY (id)
);

CREATE UNIQUE INDEX deliveries_order_uidx ON deliveries (order_id);