services:
  orders-db:
    image: postgres:16.4
    container_name: orders-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders