CREATE TABLE orders
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id INTEGER                                  NOT NULL,
    total_price INTEGER                                  NOT NULL,
    status      TEXT                                     NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE order_outbox
(
    id           UUID         NOT NULL,
    aggregate_id TEXT         NOT NULL,
    event_type   TEXT         NOT NULL,
    traceparent  TEXT         NOT NULL,
    payload      JSONB        NOT NULL,
    created_at   timestamptz  default clock_timestamp(),
    processed_at timestamptz,
    CONSTRAINT pk_orderoutbox PRIMARY KEY (id)
);

CREATE TABLE shedlock
(
    name       VARCHAR(64),
    lock_until timestamptz NULL,
    locked_at  timestamptz NULL,
    locked_by  TEXT,
    CONSTRAINT pk_schedlock PRIMARY KEY (name)
);

CREATE INDEX order_outbox_processed_at_idx ON order_outbox (processed_at) WHERE processed_at is null;